### ISSUE TITLE
Notice: Undefined index: content in ... /plugins/zz_pico_debug.php on line 118

### ISSUE THREAD

**Issue by omniperspective** [blocknotes/pico_debug#1]
Using the plugin and putting the both debug variables to TRUE I get with every pageload

[Fri Jun 17 16:23:11.556119 2016] [:error] [pid 15776] [client 66.147.240.173:57843] PHP Notice:  Undefined index: content in /home/smolensknl/domains/smolensk.nl/public_html/plugins/zz_pico_debug.php on line 118

The code:

  // Triggered when Pico reads a single page from the list of all known pages
  public function onSinglePageLoaded( array &$pageData )
  {
    $data = new ArrayObject( $pageData );
    $data['content'] = 'length: ' .  strlen( $pageData['content'] );
    $data['raw_content'] = 'length: ' .  strlen( $pageData['raw_content'] );
    $this->debug_info['onSinglePageLoaded'] = 'pageData = ' . var_export( $data->getArrayCopy(), TRUE );
  }

The line 118 
$data['content'] = 'length: ' .  strlen( $pageData['content'] ); 

I can't figure out what and why it is giving the error ??

Any hints?

**Comment by blocknotes** [comment]
I noticed that onSinglePageLoaded can be called more than once if Pico loads all the pages (example: for the menu). Added a check
